version: "3.0"
services:
        web:
                build: .
                ports:
                        - "8020:8020"
        redis:
                image: "node:12.18.3-alpine"
        labels:
                - "traefik.enable=true"
                - "traefik.http.routers.cal.rule=Host(`cart.av.cise.jmu.edu`)"
                - "traefik.http.routers.cal.entrypoints=web"
                - "traefik.http.services.cal.loadbalancer.server.port=8020"
